### ISSUE TITLE
Maintenance: Add llms.txt to documentation site

### ISSUE THREAD

**Issue by hjgraca** [aws-powertools/powertools-lambda-dotnet#892]
### Summary

Add support for llms.txt and llms-full.txt in Powertools for AWS documentation site

- llms.txt will contain the links to the sections defined on the yaml
- llms-full.txt will contain all the markdown text of those pages

### Why is this needed?

This will allow developers to add Powertools for AWS Lambda documentation context to their tools, IDEs, etc

### Solution

```yaml
plugins:
  - llmstxt:
      markdown_description: Powertools for AWS Lambda (.NET) is a developer toolkit to implement Serverless best practices and increase developer velocity. It provides a suite of utilities for AWS Lambda Functions that makes tracing with AWS X-Ray, structured logging and creating custom metrics asynchronously easier.
      full_output: llms-full.txt
      sections:
        Project Overview:
          - index.md
          - changelog.md
          - roadmap.md
        Core Utilities:
          - core/logging.md
          - core/metrics.md
          - core/tracing.md
        Utilities:
          - utilities/idempotency.md
          - utilities/batch-processing.md
          - utilities/parameters.md
          - utilities/jmespath-functions.md
          - core/event_handler/appsync_events.md
        Getting Started:
          - getting-started/logger/simple.md
          - getting-started/logger/aspnet.md
          - getting-started/logger/aot.md
```

### Acknowledgment

- [x] This request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/#tenets)
